"""add category model

Revision ID: 9e1e7140a7c9
Revises: 023800edceb4
Create Date: 2025-04-15 18:25:14.553021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e1e7140a7c9'
down_revision: Union[str, None] = '023800edceb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('model', sa.String(), nullable=True))
    op.create_foreign_key(None, 'devices', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
