"""update reqest model

Revision ID: a8b99acd02f0
Revises: 1578e26e1cd3
Create Date: 2025-04-12 11:43:52.365449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8b99acd02f0'
down_revision: Union[str, None] = '1578e26e1cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('device_id', sa.Integer(), nullable=True))
    op.add_column('requests', sa.Column('message', sa.String(), nullable=False))
    op.create_foreign_key(None, 'requests', 'devices', ['device_id'], ['id'])
    op.drop_column('requests', 'request')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('request', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'requests', type_='foreignkey')
    op.drop_column('requests', 'message')
    op.drop_column('requests', 'device_id')
    # ### end Alembic commands ###
